apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-demo-app-config
  namespace: kafka
data:
  KAFKA_BOOTSTRAP_SERVERS: "my-cluster-kafka-bootstrap:9092"
  KAFKA_TOPIC: "test-topic"
  PRODUCER_INTERVAL_SECONDS: "10"
