apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: my-cluster-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 0
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 1Gi
    deleteClaim: false
