apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000             # 7 days
    segment.bytes: 1073741824