apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    template:
      pod:
        securityContext:
          runAsUser: 1001
          runAsGroup: 0
          fsGroup: 1001
          fsGroupChangePolicy: "Always"