apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-target
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/msajidmansoori12/kafka-gitops.git
    targetRevision: mirror-maker
    path: overlays/tgt
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true          # Required for Strimzi CRD
      - SkipDryRunOnMissingResource=true